version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:${DOCKER_CACHE_DIR}/.registry

  runner:
    image: tensorpod/actions-image:latest
    restart: always
    environment:
      - REPO=tensor-works/pymimic3
      - TOKEN=${ACCESS_TOKEN}
      - DOCKER_CACHE_DIR=${DOCKER_CACHE_DIR}
      - DOCKER_BUILDKIT=1
    volumes:
      - ${DOCKER_CACHE_DIR}:${DOCKER_CACHE_DIR}
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '3'
          memory: 10G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    depends_on:
      - registry
    # network_mode: "host"

  test:
    image: tensorpod/actions-image:latest
    volumes:
      - ${DOCKER_CACHE_DIR}:${DOCKER_CACHE_DIR}
    command: [ "/test_docker_daemon_access.sh" ]
    depends_on:
      - registry

volumes:
  registry_data:
    driver: local
