services:
  runner:
    image: tensorpod/actions-image:latest
    restart: always
    environment:
      - REPO=tensor-works/pymimic3
      - TOKEN=${ACCESS_TOKEN}
      - DOCKER_CACHE_DIR=${DOCKER_CACHE_DIR}
    volumes:
      - ${DOCKER_CACHE_DIR}:${DOCKER_CACHE_DIR}
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '3'
          memory: 10G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  test:
    image: tensorpod/actions-image:latest
    volumes:
      - ${DOCKER_CACHE_DIR}:${DOCKER_CACHE_DIR}
    command: [ "/test_docker_daemon_access.sh" ]

# docker run --rm -v '//./pipe/docker_engine://var/run/docker.sock' tensorpod/actions-image:latest /test_docker_daemon_access.sh
# \\.\pipe\docker_engine:\\.\pipe\docker_engine
